eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         default-zone: http://localhost:8761/eureka
   instance:
      hostname: localhost
      
microservice:
   deploy-service:
      endpoints:
         status: http://DEPLOY-VSPHERE-TESTBED/vsphere/status/
